### PR TITLE
Create license.md

### PR DESCRIPTION
**Pull request by ghost**
Adds the MIT license, which is what I assume you want to use?

### CODE REVIEW

**Comment by ScruffyRules** [comment]
This is @Cldfire's choice.

**Comment by ghost** [comment]
I agree. Well, @Cldfire merge this if this is the license you want use.

**Comment by Cldfire** [comment]
I'll be making this decison on Sunday.

**Comment by ghost** [comment]
What about Creative Commons?

**Comment by zachbr** [comment]
I don't for one second advise using a creative commons license. Nor will I submit any code under such a license. 

MIT or GPL.

There is also a legal question here as you're adding a license _after_ multiple people have already submitted their code. Thus, you adding a license after the fact and relicensing their existing code is a grey-zone without their approval.

From CreativeCommons FAQ:

> Can I apply a Creative Commons license to software?
> 
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.
> 
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

https://creativecommons.org/faq/#Can_I_use_a_Creative_Commons_license_for_software.3F

**Comment by ghost** [comment]
The only thing I forgot about MIT (and dislike) is that it allows people to redistribute and sell it. :/

**Comment by Cldfire** [comment]
An MIT license has been added.

**Pull request closed without merging**
