### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
A small bit of information to supply to people who find this. It also makes me a contributor. :D

### CODE REVIEW

**Comment by Cldfire** [comment]
Will add to this and merge it later :)

EDIT: Or Scruffy can take care of it :3

**Comment by ScruffyRules** [comment]
Change it to XenForo not Spigot and we'll have a deal. :P

**Comment by ghost** [comment]
Fixed, sorry.

**Comment by ScruffyRules** [comment]
Cheers.

**Pull request merged**
